bank/bank/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('base.urls')),
]

bank/base/urls.py
from django.urls import path
from .views import *
from .apiviews import *
from rest_framework.routers import SimpleRouter


router = SimpleRouter()
router.register('api/users', UserViewSetApi)
router.register('api/accounts', AccountViewSetApi)


urlpatterns = [
    path('', ControlPanel.as_view(), name='control-panel'),
    path('<int:card_id>/', CardTransactionsView.as_view(), name='card-transactions'),
    path('system_info/', InfoListView.as_view(), name='info-list'),
    path('master_account_refill/', MasterAccountRefill.as_view(), name='master-account-refill'),
    path('new_org_account/', NewOrgAccount.as_view(), name='new-org-account'),
]

api_urlpatterns = [
    path('api/bankcards/', BankCardApi.as_view()),
    path('api/bankcards/<str:number>/', BankCardBalanceApi.as_view()),
    path('api/bankcard-refill/', BankCardRefill.as_view()),
    path('api/bankcard-payment/', BankCardPayment.as_view()),
    path('api/bankcard/<str:bankcard_number>/transactions/<int:n>/', BankCardTransactions.as_view()),
]

urlpatterns += router.urls
urlpatterns += api_urlpatterns

bank/base/models.py
from django.db import models
from django.utils import timezone
from datetime import date, timedelta
from django.core.exceptions import ValidationError
import random
from .constants import CURRENCIES


class User(models.Model):
    name = models.CharField(max_length=15)
    surname = models.CharField(max_length=15)
    phone_number = models.CharField(max_length=12)

    def __str__(self):
        return f'[{self.id}] {self.name} - User'


class Account(models.Model):
    owner_info = models.CharField(max_length=30)
    number = models.CharField(max_length=16, unique=True, editable=False)
    balance = models.IntegerField()
    currency = models.CharField(choices=CURRENCIES, max_length=3)
    user = models.ForeignKey(User, on_delete=models.CASCADE, blank=True, null=True)

    def __str__(self):
        if self.user:
            return f'[{self.id}] { self.user.name } - { self.balance } { self.currency } - Account'
        else:
            return f'[{self.id}] {self.owner_info} - { self.balance } { self.currency } - Account'

    def save(self, *args, **kwargs):
        if self.pk:
            super().save(*args, **kwargs)
        else:
            number = str(random.randint(0, 10000000))
            nulls = 8 - len(number)
            number = "0" * nulls + number
            self.number = '45001200' + number
            super().save(*args, **kwargs)


class BankCard(models.Model):
    account = models.ForeignKey(Account, on_delete=models.CASCADE)
    number = models.CharField(max_length=16, unique=True, editable=False)
    end_date = models.DateField(default=date.today() + timedelta(days=365))

    def __str__(self):
        return f'[{self.id}] {self.number} - BankCard'

    def save(self, *args, **kwargs):
        if self.pk:
            super().save(*args, **kwargs)
        else:
            number = str(random.randint(0, 10000000))
            nulls = 8 - len(number)
            number = "0" * nulls + number
            self.number = '45001200' + number
            super().save(*args, **kwargs)


class Transaction(models.Model):
    sum = models.IntegerField()
    currency = models.CharField(choices=CURRENCIES, max_length=3)
    date_time = models.DateTimeField(default=timezone.now)
    STATUSES = [
        ('OK', 'OK'),
        ('CANCELED', 'CANCELED'),
        ('ERROR', 'ERROR'),
        ('IN PROCESS', 'IN PROCESS'),
    ]
    status = models.CharField(choices=STATUSES, max_length=10)

    def __str__(self):
        return f'[{self.id}] {self.sum} {self.currency}'


class InnerTransaction(models.Model):
    transaction = models.OneToOneField(Transaction, on_delete=models.CASCADE)
    trans_from = models.ForeignKey(Account, on_delete=models.CASCADE, related_name='trans_from')
    trans_to = models.ForeignKey(Account, on_delete=models.CASCADE, related_name='trans_to')

    def save(self, *args, **kwargs):
        if self.pk:
            raise ValidationError('you may not edit an existing %s' % self._meta.model_name)
        else:
            super().save(*args, **kwargs)
            self.trans_from.balance -= self.transaction.sum
            self.trans_from.save()
            self.trans_to.balance += self.transaction.sum
            self.trans_to.save()
            self.transaction.status = 'OK'
            self.transaction.date_time = timezone.now()
            self.transaction.save()


class ToOuterTransaction(models.Model):
    transaction = models.OneToOneField(Transaction, on_delete=models.CASCADE)
    trans_from = models.ForeignKey(Account, on_delete=models.CASCADE)
    trans_to = models.CharField(max_length=26)

    def save(self, *args, **kwargs):
        if self.pk:
            raise ValidationError('you may not edit an existing %s' % self._meta.model_name)
        else:
            super().save(*args, **kwargs)
            self.trans_from.balance -= self.transaction.sum
            self.trans_from.save()
            self.transaction.status = 'OK'
            self.transaction.date_time = timezone.now()
            self.transaction.save()


class FromOuterTransaction(models.Model):
    transaction = models.OneToOneField(Transaction, on_delete=models.CASCADE)
    trans_from = models.CharField(max_length=26)
    trans_to = models.ForeignKey(Account, on_delete=models.CASCADE)

    def save(self, *args, **kwargs):
        if self.pk:
            raise ValidationError('you may not edit an existing %s' % self._meta.model_name)
        else:
            super().save(*args, **kwargs)
            self.trans_to.balance += self.transaction.sum
            self.trans_to.save()
            self.transaction.status = 'OK'
            self.transaction.date_time = timezone.now()
            self.transaction.save()

bank/base/forms.py
from django import forms
from .models import *
from .constants import *


class MasterAccountRefillForm(forms.Form):
    refill = forms.IntegerField()


class NewOrgForm(forms.Form):
    INN = forms.IntegerField()
    balance = forms.IntegerField()

bank/base/views.py
from django.shortcuts import render
from django.views.generic import View
from .models import *
from .utils import get_bankcard_transactions
from .forms import *


class ControlPanel(View):
    def get(self, request):
        context = {
            'title': 'Control Panel',
            'bankcards': BankCard.objects.all()
        }
        return render(request, 'base/panel.html', context=context)


class CardTransactionsView(View):
    def get(self, request, card_id):
        n = Transaction.objects.all().count()
        data = get_bankcard_transactions(BankCard.objects.get(id=card_id).account, n)
        print(data)
        context = {
            'card_id': card_id,
            'data': data,
            'title': 'Bank Card Transactions',
        }
        return render(request, 'base/card_transactions.html', context=context)


class InfoListView(View):

    def get(self, request):
        users = User.objects.all()
        accounts = Account.objects.all()
        bankcards = BankCard.objects.all()
        transactions = Transaction.objects.all()
        inner_transactions = InnerTransaction.objects.all()
        to_outer_transactions = ToOuterTransaction.objects.all()
        from_outer_transactions = FromOuterTransaction.objects.all()

        context = {
            'users': users,
            'accounts': accounts,
            'bankcards': bankcards,
            'transactions': transactions,
            'inner_transactions': inner_transactions,
            'to_outer_transactions': to_outer_transactions,
            'from_outer_transactions': from_outer_transactions,
            'title': 'System Info',
        }
        return render(request, 'base/info.html', context=context)


class MasterAccountRefill(View):

    def get(self, request):
        context = {
            'form': MasterAccountRefillForm,
            'balance': Account.objects.get(id=2).balance,
            'title': 'Master Account Refill',
        }
        return render(request, 'base/master_account_refill.html', context=context)

    def post(self, request):
        refill = request.POST.get("refill")
        master_account = Account.objects.get(id=2)
        master_account.balance += int(refill)
        master_account.save()
        context = {
            'form': MasterAccountRefillForm,
            'message': f'Master Account Delta = {refill} RUB',
            'balance': Account.objects.get(id=2).balance,
            'title': 'Master Account Refill',
        }
        return render(request, 'base/master_account_refill.html', context=context)


class NewOrgAccount(View):

    def get(self, request):
        context = {
            'form': NewOrgForm,
            'title': 'New Organization Account',
            'message': 'Only RUB account creation available',
        }
        return render(request, 'base/new_org_account.html', context=context)

    def post(self, request):
        owner_info = request.POST.get("INN")
        balance = request.POST.get("balance")
        currency = "RUB"
        account = Account.objects.create(owner_info=owner_info, balance=balance, currency=currency)
        context = {
            'message': 'New Organization Account created:',
            'account': account,
            'title': 'New Organization Account',
        }
        return render(request, 'base/new_org_account.html', context=context)

bank/base/templates/base/base.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">

    {% if title %}
        <title>Abstract Admin - {{ title }}</title>
    {% else %}
        <title>Abstract Admin</title>
    {% endif %}

</head>
<body>
    {% block content %}
    {% endblock %}
</body>
</html>

bank/base/templates/base/card_transactions.html
{% extends "base/base.html" %}
{% block content %}

    <h1>Control Panel</h1>
    <a href="{% url 'control-panel' %}">Back to Control Panel</a><br><br>

    <h3>Bank Card Transactions (Card ID: {{ card_id }}):</h3>
    {% for dict in data %}
        {{ dict }}<br>
    {% endfor %}
    <br>
    <br>


{% endblock content %}

bank/base/templates/base/info.html
{% extends "base/base.html" %}
{% block content %}

    <h1>System Info</h1>
    <a href="{% url 'control-panel' %}">Back to Control Panel</a><br><br>

    <h2>Users:</h2>

    {% for user in users %}
        User ID: [{{user.id}}]<br>
        Name: {{ user.name }}<br>
        Surname: {{ user.surname }}<br>
        Phone Number: {{ user.phone_number }}<br>
        <h4>&emsp;Accounts:</h4>
        {% for account in user.account_set.all %}
            &emsp;Account ID: [{{account.id}}]<br>
            &emsp;Account Owner Info: {{ account.owner_info }}<br>
            &emsp;Account Number: {{ account.number }}<br>
            &emsp;Account Balance: {{ account.balance }}<br>
            &emsp;Account Currency: {{ account.currency }}<br>
            <h4>&emsp;&emsp;Bank Cards:</h4>
                {% for bankcard in account.bankcard_set.all %}
                 &emsp;&emsp;Bank Card ID [{{bankcard.id}}]<br>
                 &emsp;&emsp;Bank Card Number: {{ bankcard.number }}<br>
                 &emsp;&emsp;Bank Card End Date: {{ bankcard.end_date }}<br>
                 &emsp;&emsp;Balance: {{ account.balance }}<br>
                 &emsp;&emsp;Currency: {{ account.currency }}<br>
                {% endfor %}
            <br>
        {% endfor %}
    {% endfor %}
    <br>
    <br>

    <h2>Accounts:</h2>

    {% for account in accounts %}
        Account ID: [{{ account.id }}]<br>
        Owner Info: {{ account.owner_info }}<br>
        Balance: {{ account.balance }}<br>
        Currency: {{ account.currency }}<br>
        {% if account.user %}
            User: {{ account.user }} {{ account.user.id }}<br>
        {% endif %}
        <br>
    {% endfor %}

    <h2>Transactions:</h2>

    {% for transaction in transactions %}
        Transaction ID: [{{ transaction.id }}]<br>
        Sum: {{ transaction.sum}}<br>
        Currency: {{ transaction.currency }}<br>
        Date Time: {{ transaction.date_time }}<br>
        Status: {{ transaction.status }}<br>

        {% if transaction.innertransaction %}
            Type: Inner Transaction<br>
            Account ID Trans from: [{{ transaction.innertransaction.trans_from.id }}] {{ transaction.innertransaction.trans_from.owner_info }}<br>
            Account ID Trans to: [{{ transaction.innertransaction.trans_to.id }}]<br>
        {% endif %}

        {% if transaction.tooutertransaction %}
            Type: To Outer Transaction<br>
            Account ID Trans from: [{{ transaction.tooutertransaction.trans_from.id }}] {{ transaction.tooutertransaction.trans_from.id.owner_info }}<br>
            Info Trans to: {{ transaction.tooutertransaction.trans_to }}<br>
        {% endif %}

        {% if transaction.toinnertransaction %}
            Type: To Inner Transaction<br>
            Info Trans from: {{ transaction.innertransaction.trans_from }}<br>
            Account ID Trans to: [{{ transaction.toinnertransaction.trans_to.id }}] {{ transaction.toinnertransaction.trans_to.id.owner_info }}<br>
        {% endif %}
        <br>
    {% endfor %}

{% endblock content %}

bank/base/templates/base/master_account_refill.html
{% extends "base/base.html" %}
{% block content %}

    <h1>Master Account Refill</h1>
    <a href="{% url 'control-panel' %}">Back to Control Panel</a><br><br>

    {% if message %}
        {{ message }}<br>
    {% endif %}

    Master Account Balance: {{ balance }} RUB<br><br>

    {% if form %}
        <form action="{% url 'master-account-refill' %}" method="post">
            {% csrf_token %}
            {% for field in form %}
                {% if field.errors %}
                    {{ field.errors }}
                {% endif %}
                Balance refill, RUB:
                {{ field }}
            {% endfor %}
            <button type="submit">Refill</button>
        </form>
    {% endif %}

{% endblock content %}

bank/base/templates/base/new_org_account.html
{% extends "base/base.html" %}
{% block content %}

    <h1>New Org Account</h1>
    <a href="{% url 'control-panel' %}">Back to Control Panel</a><br><br>

    {% if message %}
        {{ message }}<br>
    {% endif %}

    {% if form %}
        <form action="{% url 'new-org-account' %}" method="post">
            {% csrf_token %}
            {% for field in form %}
                {% if field.errors %}
                    {{ field.errors }}
                {% endif %}
                {{ field.label }}
                {{ field }}
            {% endfor %}
            <button type="submit">Create</button>
        </form>
    {% endif %}

    {% if account %}
        Account ID: {{ account.id }}<br>
        Account owner INN: {{ account.owner_info }}<br>
        Account Balance: {{ account.balance }}<br>
        Account Currency: {{ account.currency }}<br>
    {% endif %}

{% endblock content %}

bank/base/templates/base/panel.html
{% extends "base/base.html" %}
{% block content %}
<h1>Control Panel</h1>

<a href="{% url 'info-list' %}">System Info</a><br>
<a href="{% url 'master-account-refill' %}">Master Account Refill</a><br>
<a href="{% url 'new-org-account' %}">Add company account</a><br>

<h3>All Bank Cards:</h3>
{% for card in bankcards %}
    Card ID: {{ card.id }}<br>
    Card Number: {{ card.number }}<br>
    Card End Date: {{ card.end_date }}<br>
    Card Balance: {{ card.account.balance }} {{ card.account.currency }}<br>
    Card Owner: {{ card.account.user.name }} {{ card.account.user.surname }}<br>
    <a href="{% url 'card-transactions' card.id %}">Card Transactions</a>
{% endfor %}

<br>
<br>


{% endblock content %}